### ISSUE TITLE
Getting "Runtime error encountered: No Chrome installations found." on running Lighthouse command

### ISSUE THREAD

**Issue by Dbroug01** [justinribeiro/dockerfiles#50]
I have tried to run this as per the README and also tried to build a new image based on the Dockerfile, but in both instances, I am getting: _"Runtime error encountered: No Chrome installations found."_ when I try to run your example Lighthouse command.

Do you know why this would be and how I can fix it?

**Comment by justinribeiro** [comment]
I've pushed a small fix for this; it should build successfully now (at least in my test runs it now does). 

If you're still having issues building and running, feel free to reopen and let me know what platform you're building on.

**Comment by Dbroug01** [comment]
I'm still getting this issue when I try to run the Lighthouse command. The Dockerfile builds and drops to CLI perfectly, but it cannot find Chrome still, here is the error message:

````
Runtime error encountered: No Chrome installations found.
Error
    at new LauncherError (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:35:22)
    at new ChromeNotInstalledError (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/utils.js:66:9)
    at Launcher.<anonymous> (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:146:27)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/lighthouse/node_modules/chrome-launcher/dist/chrome-launcher.js:9:58)
````

I am running this on WSL2, do you think that could be affecting this?

Thanks,

Darcey

**Comment by justinribeiro** [comment]
Humm, yeah, I'm not having this issues on any of my linux deploys; let me fire up WSL2 and see what's cooking.
