### ISSUE TITLE
justinribeiro/lighthouse timeout

### ISSUE THREAD

**Issue by rafipiccolo** [justinribeiro/dockerfiles#58]
when i run this i get a timeout.
but the exemple from the readme works. 

It looks like disconnecting from browser takes 2 minutes :)
its a bit excessive because when auditing this website (https://justinribeiro.com) it disconnects in 4ms.
do you have any clue ?

```
#> mkdir test
#> cd test
#> docker run --rm -itv "$(pwd):/home/chrome/reports" --cap-add=SYS_ADMIN justinribeiro/lighthouse
#> lighthouse --chrome-flags="--headless --disable-gpu" https://flatbay.fr/fr
  ChromeLauncher Waiting for browser. +0ms
  ChromeLauncher Waiting for browser... +1ms
  ChromeLauncher Waiting for browser..... +506ms
  ChromeLauncher Waiting for browser.....✓ +1ms
  config:warn Trace not requested by an audit, dropping trace in defaultPass +565ms
  status Connecting to browser +2ms
  status Resetting state with about:blank +15ms
  status Benchmarking machine +20ms
  status Initializing… +1s
  status Running defaultPass pass FullPageScreenshot +637ms
  status Resetting state with about:blank +0ms
  status Setting up network for the pass trace +9ms
  status Beginning devtoolsLog and trace +2ms
  status Loading page & waiting for onload +0ms
  status Gathering in-page: FullPageScreenshot +3s
  status Gathering devtoolsLog & network records +0ms
  status Gathering: FullPageScreenshot +10ms
  status Disconnecting from browser... +2m
  ChromeLauncher Killing Chrome instance 501 +2ms
Runtime error encountered: Waiting for DevTools protocol response has exceeded the allotted time. (Method: Runtime.evaluate)
LHError: PROTOCOL_TIMEOUT
    at Timeout._onTimeout (/usr/lib/node_modules/lighthouse/lighthouse-core/gather/driver.js:376:21)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by justinribeiro** [comment]
Humm, can't dup it the error on the latest image:
![image](https://user-images.githubusercontent.com/643503/117078543-ec34a880-acee-11eb-87a2-2e4b562a629f.png)

I have a set of rebuilds happening at moment, let me see if a lighthouse rev bump solves it.

**Comment by rafipiccolo** [comment]
i went on another machine (ubuntu) in another datacenter.
i pulled latest img right now.
i started the very same commands
same situation. :(

i guess lighthouse is not for my websites :)
